return {
    BOX_ERROR = 0x01,
    WRONG_BUCKET = 0x02,
    NON_MASTER = 0x03,
    BUCKET_ALREADY_EXISTS = 0x04,
    NO_SUCH_REPLICASET = 0x05,
    MOVE_TO_SELF = 0x06,
    MISSING_MASTER = 0x07,
    TRANSFER_IS_IN_PROGRESS = 0x08,
    REPLICASET_IS_UNREACHABLE = 0x09,
    NO_ROUTE_TO_BUCKET = 0x0a,
}
