name: catch_flaky

on:
  pull_request:
    paths:
      - 'test/*/*_test.lua'
      - 'test/*/*.test.lua'

jobs:
  catch_flaky:
    if: github.event_name == 'pull_request' &&
        !contains(github.event.pull_request.labels.*.name, 'noflaky')

    runs-on: ubuntu-22.04
    timeout-minutes: 180
    steps:
      - name: Clone the module
        uses: actions/checkout@v3
        with:
          # Fetch the entire history for all branches and tags. It is needed for
          # upgrade testing.
          fetch-depth: 0
          # Enable recursive submodules checkout as test-run git module is used
          # for running tests.
          submodules: recursive
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup Tarantool
        uses: ./.github/actions/setup-tarantool
        with:
          tarantool_version: release-master

      - name: Install test requirements
        run: pip3 install --user -r test-run/requirements.txt

      - name: Setup tt
        run: |
          curl -L https://tarantool.io/release/2/installer.sh | sudo bash
          sudo apt install -y tt
          tt version

      - name: Setup luatest
        run: tt rocks install luatest 1.4.1

      - run: cmake .
      - run: make test-flaky
        env:
          RANGE: HEAD~${{ github.event.pull_request.commits }}..HEAD
